"""Nightly statistical analysis (Phase 3).

This package splits the former single ``analysis.py`` into role-based modules so
each layer is read and tested on its own, while preserving the flat public API:
``from app.analysis import X`` and ``app.analysis.X`` resolve exactly as before.

- ``constants`` — tunables (mirroring ``AnalysisConfig`` defaults) + structural
  domain constants.
- ``pure`` — pure math (no DB/IO): correlation, decomposition, TRIMP, HR
  resolution. Unit-tested against synthetic series.
- ``load`` — DB loaders turning queries into daily series / per-session frames.
- ``findings`` — series assembly + the finding builders for each kind.
- ``run`` — orchestration (``run`` + ``main``); ``__main__`` makes
  ``python -m app.analysis`` run it as the scheduler's subprocess.

Findings (ARCHITECTURE.md §4.8), all derived, never medical advice:
- correlation    Spearman on de-trended series, lags 0..3 days (both
                 directions), FDR-corrected, best lag/direction per pair.
- anomaly        28-day trailing median + MAD robust z; only recent days.
- trend          long-run drift (slope of the trend component + strength).
- seasonality    MSTL(7, 365): annual pattern (amplitude + peak/trough month,
                 with a phase-confidence flag when peak/trough are too close).
- recovery_alert composite early warning: HRV low AND resting HR high together.
- consistency    rolling variability of sleep duration and bedtime.
- training_load  ACWR (acute:chronic workload ratio) on daily workout load,
                 overall and per sport; flagged on a load spike or detraining
                 (Banister TRIMP / kcal).
- stress         alert-only high-stress day; the continuous intraday score +
                 daily summary live in the stress tables (see stress.py, §4.9).
- body_battery   alert-only low-battery day; the continuous 0-100 energy-reserve
                 timeline + daily summary live in the body-battery tables (see
                 body_battery.py, §4.10).
"""

from __future__ import annotations

from .constants import (
    ACWR_ACUTE_DAYS,
    ACWR_CHRONIC_DAYS,
    ANOMALY_MIN_GLOBAL_Z,
    ANOMALY_RECENT_DAYS,
    ANOMALY_THRESHOLD,
    ANOMALY_WINDOW,
    CONSISTENCY_BEDTIME_STD,
    CONSISTENCY_DURATION_STD,
    CONSISTENCY_WINDOW,
    CORR_KEEP_ALPHA,
    CORR_MIN_ABS,
    CORR_MIN_ACTIVE,
    CORR_RAW_MIN_ABS,
    FDR_ALPHA,
    HR_MAX_DATA_CEIL,
    HR_MAX_DATA_FLOOR,
    HR_MAX_FALLBACK,
    HR_REST_FALLBACK,
    HR_REST_MIN_PERIODS,
    HR_REST_WINDOW,
    MAX_LAG,
    MIN_OVERLAP,
    RECOVERY_RECENT_DAYS,
    RECOVERY_SLEEP_Z,
    RECOVERY_Z,
    SEASONAL_MIN_PEAK_TROUGH_GAP,
    SEASONAL_MIN_SHARED_MONTHS,
    SEASONAL_PERIOD,
    SEASONALITY_REPRODUCIBILITY_MIN,
    SEASONALITY_STRENGTH_MIN,
    TREND_MIN_MONOTONICITY,
    TREND_STRENGTH_MIN,
    WEEK_PERIOD,
    log,
)
from .findings import (
    _APPLE_ACTIVITY_METRICS,
    _WORKOUT_LOAD_FAMILY,
    AnalysisResult,
    _active_days,
    _anomaly_findings,
    _consistency_findings,
    _correlation_findings,
    _decompose_all,
    _dedupe_workout_anomalies,
    _detrended_series,
    _emit_edwards,
    _is_activity_volume,
    _is_redundant_activity_pair,
    _is_workout_load_family,
    _load_columns,
    _metric_domain,
    _pair_tier,
    _recovery_findings,
    _residual_for_correlation,
    _residual_series,
    _training_load_findings,
    _training_load_targets,
    _trend_and_seasonality_findings,
    build_series,
    build_workout_series,
    core_metrics,
    report_priority,
)
from .load import (
    _reindex_full,
    _series_from_rows,
    load_daily_series,
    load_sleep_frame,
    load_workout_frame,
    load_workout_hr_samples,
)
from .pure import (
    EDWARDS_ZONE_LOWER,
    Corr,
    Decomp,
    _component_strength,
    _daily_grid,
    _global_robust_z,
    _hr_zone_weight,
    _mad,
    _prepare_series,
    _seasonal_reproducibility,
    acute_chronic_ratio,
    aggregate_workout_daily,
    annual_seasonality,
    banister_trimp,
    body_battery_timeline,
    circular_bedtime_offset,
    decompose,
    edwards_trimp,
    fdr_adjust,
    fill_zero_within_span,
    resolve_hr_max,
    resolve_hr_rest,
    robust_z,
    rolling_mad_anomalies,
    spearman_lag,
    stress_intraday_from_hr,
    stress_state,
    summarize_body_battery_day,
    summarize_stress_day,
    trend_monotonicity,
    trend_slope,
)
from .run import main, run

__all__ = [
    "ACWR_ACUTE_DAYS",
    "ACWR_CHRONIC_DAYS",
    "ANOMALY_MIN_GLOBAL_Z",
    "ANOMALY_RECENT_DAYS",
    "ANOMALY_THRESHOLD",
    "ANOMALY_WINDOW",
    "AnalysisResult",
    "CONSISTENCY_BEDTIME_STD",
    "CONSISTENCY_DURATION_STD",
    "CONSISTENCY_WINDOW",
    "CORR_KEEP_ALPHA",
    "CORR_MIN_ABS",
    "CORR_MIN_ACTIVE",
    "CORR_RAW_MIN_ABS",
    "Corr",
    "Decomp",
    "EDWARDS_ZONE_LOWER",
    "FDR_ALPHA",
    "HR_MAX_DATA_CEIL",
    "HR_MAX_DATA_FLOOR",
    "HR_MAX_FALLBACK",
    "HR_REST_FALLBACK",
    "HR_REST_MIN_PERIODS",
    "HR_REST_WINDOW",
    "MAX_LAG",
    "MIN_OVERLAP",
    "RECOVERY_RECENT_DAYS",
    "RECOVERY_SLEEP_Z",
    "RECOVERY_Z",
    "SEASONALITY_REPRODUCIBILITY_MIN",
    "SEASONALITY_STRENGTH_MIN",
    "SEASONAL_MIN_PEAK_TROUGH_GAP",
    "SEASONAL_MIN_SHARED_MONTHS",
    "SEASONAL_PERIOD",
    "TREND_MIN_MONOTONICITY",
    "TREND_STRENGTH_MIN",
    "WEEK_PERIOD",
    "_APPLE_ACTIVITY_METRICS",
    "_WORKOUT_LOAD_FAMILY",
    "_active_days",
    "_anomaly_findings",
    "_component_strength",
    "_consistency_findings",
    "_correlation_findings",
    "_daily_grid",
    "_decompose_all",
    "_dedupe_workout_anomalies",
    "_detrended_series",
    "_emit_edwards",
    "_global_robust_z",
    "_hr_zone_weight",
    "_is_activity_volume",
    "_is_redundant_activity_pair",
    "_is_workout_load_family",
    "_load_columns",
    "_mad",
    "_metric_domain",
    "_pair_tier",
    "_prepare_series",
    "_recovery_findings",
    "_reindex_full",
    "_residual_for_correlation",
    "_residual_series",
    "_seasonal_reproducibility",
    "_series_from_rows",
    "_training_load_findings",
    "_training_load_targets",
    "_trend_and_seasonality_findings",
    "acute_chronic_ratio",
    "aggregate_workout_daily",
    "annual_seasonality",
    "banister_trimp",
    "body_battery_timeline",
    "build_series",
    "build_workout_series",
    "circular_bedtime_offset",
    "core_metrics",
    "decompose",
    "edwards_trimp",
    "fdr_adjust",
    "fill_zero_within_span",
    "load_daily_series",
    "load_sleep_frame",
    "load_workout_frame",
    "load_workout_hr_samples",
    "log",
    "main",
    "report_priority",
    "resolve_hr_max",
    "resolve_hr_rest",
    "robust_z",
    "rolling_mad_anomalies",
    "run",
    "spearman_lag",
    "stress_intraday_from_hr",
    "stress_state",
    "summarize_body_battery_day",
    "summarize_stress_day",
    "trend_monotonicity",
    "trend_slope",
]
